# Generated by Django 4.2.5 on 2023-09-18 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_coupon_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon_Code',
        ),
    ]
